name: 'Setup python'
description: 'Setup python and required packages'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install python dependencies
      shell: bash
      run: |
        pip install -r requirements.txt